        DEFINE  tmode  3
        DEFINE  tiles  96
        DEFINE  bmaps  47
        DEFINE  attrs  25
        DEFINE  smooth 1
        DEFINE  clipup 2
        DEFINE  clipdn 2
        DEFINE  cliphr 0
        DEFINE  safevr 1
        DEFINE  safehr 1
        DEFINE  offsex 1
        DEFINE  offsey 0
        DEFINE  notabl 1
        DEFINE  bullet 1
        DEFINE  bulmax 4
        DEFINE  sprmax 5
        DEFINE  bulmiy 2
        DEFINE  bulmay 6
        DEFINE  player 2772
