// External custom code to be run from a script
void waitkeyandclean()
{
	unsigned char gg;

	gg = (joyfunc) (&keys);
	while(! ((gg & sp_FIRE) == 0) ) {
		sp_UpdateNow();
		gg = (joyfunc) (&keys);
	}
	
	while( ((gg & sp_FIRE) == 0) ) {
		sp_UpdateNow();
		gg = (joyfunc) (&keys);
	}
	for(gg=0; gg<16; gg++)
	{
		print_str (0, gg,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "                                ");
	}
}

void pasaFrase(const char *frase, unsigned char color)
{
	unsigned char z;
	unsigned int i;
	unsigned char gg;
	i=28;
	
	while(frase[i]!='\0')
	{
		z=frase[i];
		frase[i]='\0';
		print_str (2, 22,  color, frase+i-28);
		frase[i]=z;
		i=i+1;
		sp_UpdateNow();
		gg = (joyfunc) (&keys);
		if( !((gg & sp_FIRE) == 0))
		{
			espera_activa (20);
		}
	}
}

void muestraTexto(unsigned char n) {
	if(n==0)
	{
		for(n=0; n<16; n++)
		{
			print_str (0, n,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "                                ");
		}
		print_str (0, 1,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "************* HAN **************");
		print_str (0, 3,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "ORDENADOR, ABRE DIARIO DE BITACORA #11038. ENTRADA NUEVA POR HAN LOPEZ, EMPLEADO DE HSPS CODIGO T19H071X. ULTIMAMENTE ELLEN Y YO NOS SENTIMOS MUY CANSADOS. ADEMAS, SEGUIMOS SIN CONEXION CON LA ESTACION CENTRAL.");
		waitkeyandclean();
		//pasaFrase("        ORDENADOR, ABRE DIARIO DE BITACORA #11038. ENTRADA NUEVA POR HAN LOPEZ, EMPLEADO DE HSPS CODIGO T19H071X. PIENSO QUE OCURRE ALGO RARO. TARDAMOS MUCHO EN VOLVER A CASA. PARECE TODO CORRECTO, PERO AYER PASAMOS POR DELANTE DE UNA ESTRELLA QUE NO LOGRE RECONOCER.   ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		//pasaFrase("        PIENSO QUE OCURRE ALGO RARO. TARDAMOS MUCHO EN VOLVER A CASA. PARECE TODO CORRECTO, PERO AYER PASAMOS POR DELANTE DE UNA ESTRELLA QUE NO LOGRE RECONOCER.     ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		//pasaFrase("        ULTIMAMENTE ELLEN Y YO NOS SENTIMOS MUY CANSADOS. ADEMAS, SEGUIMOS SIN CONEXION CON LA ESTACION CENTRAL.    ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		//pasaFrase("        ESTOY DESEANDO LLEGAR A CASA, Y BEBERME UNA BIRRA HELADA.      ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		
		print_str (0, 1,  COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "************* CPU **************");
		print_str (0, 3,  COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "HAN, NOS QUEDA POCO COMBUSTIBLE DE RESERVA, Y LOS MOTORES LLEVAN MUCHO TIEMPO ENCENDIDOS. RECOMIENDO QUE PAREMOS EN ESE PLANETA QUE PUEDE VER A SU IZQUIERDA. SEGUN MI BASE DE DATOS CUENTA CON UN CENTRO DE SUMINISTROS.");
		waitkeyandclean();
		//pasaFrase("        HAN, NOS QUEDA POCO COMBUSTIBLE DE RESERVA, Y LOS MOTORES LLEVAN MUCHO TIEMPO ENCENDIDOS. RECOMIENDO QUE PAREMOS EN ESE PLANETA QUE PUEDE VER A SU IZQUIERDA. SEGUN MI BASE DE DATOS CUENTA CON UN CENTRO DE SUMINISTROS.    ", COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
		
		print_str (0, 1,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "************* HAN **************");
		print_str (0, 3,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "OK, NOS VENDRA BIEN A TODOS SALIR DE ESTA LATA DE SARDINAS.");
		waitkeyandclean();
		//pasaFrase("        OK, NOS VENDRA BIEN A TODOS SALIR DE ESTA LATA DE SARDINAS.       ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		
		//pasaFrase("        NO HAY PROBLEMA HAN. EL PORCENTAJE DE LOGRAR UN ATERRIZAJE OPTIMO ES DEL 99%.      ", COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
		print_str (0, 1,  COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "************ CAPITAN ***********");
		print_str (0, 3,  COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "ORDENADOR, ANALIZA EL COMPLEJO POR QUE NO HEMOS RECIBIDO NINGUNA TRANSMISION DE BIENVENIDA?.");
		waitkeyandclean();
		
		
		print_str (0, 1,  COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "************* CPU **************");
		print_str (0, 3,  COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "NO LOCALIZO FORMAS DE VIDA. PARECE SER QUE ABANDONARON EL COMPLEJO POR FALTA DE ACTIVIDAD. TODAVIA FUNCIONAN LOS PANELES SOLARES. EL AIRE ESTA RECICLADO EN UN 55%. SEGUN LA BASE DE DATOS TIENEN COMBUSTIBLE EN EL ALMACEN.");
		waitkeyandclean();
	}
	
	if(n==1)
	{
		//pasaFrase("        ORDENADOR, ANALIZA EL COMPLEJO POR QUE NO HEMOS RECIBIDO NINGUNA TRANSMISION DE BIENVENIDA?.     ", COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
		//pasaFrase("        NO LOCALIZO FORMAS DE VIDA. PARECE SER QUE ABANDONARON EL COMPLEJO POR FALTA DE ACTIVIDAD.      ", COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		//pasaFrase("        TODAVIA FUNCIONAN LOS PANELES SOLARES. EL AIRE ESTA RECICLADO EN UN 55%. SEGUN LA BASE DE DATOS TIENEN COMBUSTIBLE EN EL ALMACEN.      ", COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
		pasaFrase("        HAN, VE A MIRAR SI ENCUENTRAS COMBUSTIBLE EN EL ALMACEN. ELLEN, ECHA UNA OJEADA DE MIENTRAS, A VER SI HAY ALGO COMESTIBLE.       ", COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);

		pasaFrase("        OK CAPITAN, ESTOY HARTA DE BARRITAS ENERGETICAS.      ", COLOR_ROJO_FOREGROUND+COLOR_AZUL_FOREGROUND+COLOR_LIGHT);
	}
	
	if(n==2)
	{
		//coges el combustible y ellen grita
		pasaFrase("       AQUI ESTA EL COMBUSTIBLE.     ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		
		pasaFrase("       SOCORRO!!!! QUE ALGUIEN ME AYUDE!!!! AQUI ARRIBA!!!!!!.       ", COLOR_ROJO_FOREGROUND+COLOR_AZUL_FOREGROUND+COLOR_LIGHT);
	}
	
	if(n==3)
	{
		//salvas a ellen
		pasaFrase("       GRACIAS! LAS DEFENSAS DE LA BASE ESTAN ACTIVAS... VOY A REGRESAR CON EL COMBUSTIBLE, COMPRUEBA SI HAY ALGO MAS QUE NOS AYUDE.        ", COLOR_ROJO_FOREGROUND+COLOR_AZUL_FOREGROUND+COLOR_LIGHT);
	
		pasaFrase("       TENEMOS UN PROBLEMA HAN. EL CAPITAN SE ESTA COMPORTANDO DE FORMA ERRATICA. CREO QUE ESTAMOS EN PELIGRO... NECESITO QUE VAYA AL SECTOR C Y ENCUENTRE UN ARMA...      ", COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
	}
	
	if(n==4)
	{

		pasaFrase("       #011988. HEMOS CREADO EL ANTIVIRUS PERO HEMOS LLEGADO TARDE, TODOS HAN MUERTO Y YO ME QUEDO SIN OXIGENO...     ", COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
		pasaFrase("       HAN, REGRESA INMEDIATAMENTE A LA NAVE! EL CAPITAN HA ATACADO A ELLEN!.     ", COLOR_AZUL_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
		
		pasaFrase("       AQUI PASA ALGO RARO, TENGO QUE VOLVER, COPIARE EL ANTIVIRUS.      ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
	}
	
	if(n==5)
	{
		//nos enfrentamos ante el ordenador
		pasaFrase("      QUE HA OCURRIDO?    ", COLOR_BLANCO_FOREGROUND+COLOR_LIGHT);
		
		pasaFrase("      AYUDA! EL ORDENADOR SE HA VUELTO LOCO! QUIERE MATARNOS! USA EL ANTIVIRUS PARA DERROTARLO!    ", COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
	}
	
	if(n==6)
	{
		//conversacion final
		for(n=0; n<16; n++)
		{
			print_str (0, n,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "                                ");
		}
		print_str (0, 1,  COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "*********** CAPITAN ************");
		print_str (0, 3,  COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "TE LO DIJE ELLEN, EL ANTIVIRUS FUNCIONA.");
		waitkeyandclean();
		
		print_str (0, 1,  COLOR_ROJO_FOREGROUND+COLOR_AZUL_FOREGROUND+COLOR_LIGHT, "************ ELLEN *************");
		print_str (0, 3,  COLOR_ROJO_FOREGROUND+COLOR_AZUL_FOREGROUND+COLOR_LIGHT, "INCREIBLE. VAMOS A TENER QUE ANALIZAR EL CODIGO PARA REFORZAR NUESTRO VIRUS, SI QUEREMOS APODERARNOS DEL SISTEMA CENTRAL.");
		waitkeyandclean();
		
		print_str (0, 1,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "************* HAN **************");
		print_str (0, 3,  COLOR_BLANCO_FOREGROUND+COLOR_LIGHT, "ESTAIS DETRAS DE TODO ESTO!?");
		waitkeyandclean();
		
		print_str (0, 1,  COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "*********** CAPITAN ************");
		print_str (0, 3,  COLOR_ROJO_FOREGROUND+COLOR_VERDE_FOREGROUND+COLOR_LIGHT, "LO SIENTO HAN. HACE MAS DE 10 ANOS, LA CORPORACION BOOOBLE COMENZO A EXPERIMENTAR CON UN VIRUS CAMUFLADO EN UN VIDEOJUEGO, CAPAZ DE APODERARSE DEL CONTROL DE CUALQUIER SISTEMA.");
		waitkeyandclean();
/*
¿Cuántos paquetes sin remitente has entregado durante todo este tiempo, Han? Miles. Prácticamente cualquier sistema está controlado por nosotros.

En esta pequeña base fueron capaces de descubrir sus intenciones, e incluso de lograr un antivirus. Ahora hemos decidido recuperarlo, y tú lo has conseguido. Te agradecemos el esfuerzo, pero vamos a tener que eliminarte.

Han: Parece que tengo mucha faena por delante. Esa birra helada tendrá que esperar.
*/
	}
	
	if(n==40)
	{
		pasaFrase("      #011968: HOY HA LLEGADO LA NAVE DE REPARTO DE HSPS. ENTRE LA MERCANCIA FIGURABA UN PAQUETE SIN REMITENTE.    ", COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
	}
	
	if(n==41)
	{
		pasaFrase("      #011970. EL PAQUETE SIN REMITENTE QUE RECIBIMOS EL OTRO DIA ERA UN VIDEOJUEGO DE UNA RANA QUE DEBE RESCATAR A UNA PRINCESA. NUESTROS EXPERTOS LO ESTAN ANALIZANDO.    ", COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
	}
	
	
	if(n==42)
	{
		pasaFrase("      #011973. EL VIDEOJUEGO SE HA APODERADO DEL SISTEMA! NUESTROS EXPERTOS TRABAJAN EN UN MODO DE DESHACERSE DE EL.   ", COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
	}
	
	
	if(n==43)
	{
		pasaFrase("      #011980. LA UNICA FORMA DE ACABAR CON LA INFECCION.... RECUPERAR SOFTWARE ANTIVIRUS EN SECTOR C.....     ", COLOR_VERDE_FOREGROUND+COLOR_LIGHT);
	}

}

void do_extern_action (unsigned char n) {
	// Add custom code here.	
	if(n>9)
	{
		muestraTexto(n-10);
	}
	/*if(n>49)
	{
		muestraTexto(n-10);
	}*/
	
}



